# Generated by Django 5.0.3 on 2024-10-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
