# Generated by Django 5.0.3 on 2024-10-13 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='social_foll_followe_9bcca8_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='social_foll_followi_3e6f69_idx'),
        ),
    ]
